API_REGISTER = '/m/api/register'
API_LOGIN = '/m/api/login'
API_FORGET = '/m/api/forget'
API_GET_VERIFY_CODE = '/m/api/generate_verify_code'
API_APPOINTMENT = '/api/appointment'
URL_REGISTER = '/m/register'
URL_LOGIN = '/m/login'
URL_FORGET = '/m/forget'
URL_LOGIN_PHONE = '/m/login_phone'
URL_TERMS = '/m/agreement/terms'
URL_PRIVACY = '/m/agreement/privacy'

URL_ADV = '/m/'
URL_NEWS = '/m/news'

URL_INVEST = '/m/invest'
API_FUNDS = '/api/funds'
URL_INVESTOR = '/m/invest/investor'
URL_PROD = '/m/invest/prod'
URL_PAY = '/m/invest/pay'
URL_APPOINTMENT = '/m/invest/appointment'
API_ENTITY = '/fund_america/entities'
API_AGREEMENT = '/fund_america/subscription_agreements'
API_SIGN = '/fund_america/electronic_signatures'
API_ACH = '/fund_america/achs'
API_INVEST = '/fund_america/investments'
API_ORDER = '/api/orders'
URL_ACH = '/m/agreement/ach'
URL_AGREE = '/m/agreement/agree'

URL_MYSELF = '/m/myself'
URL_FUNDS = '/m/myself/funds'
URL_CONTACT = '/m/myself/contact'
URL_ABOUT_US = '/m/myself/about_us'
URL_SUGGEST = '/m/myself/suggest'
URL_SUPPORT = '/m/myself/support'
URL_INVITE = '/m/myself/invite'
URL_SETTING = '/m/myself/setting'
URL_CHANGE_LOGIN_PHONE = '/m/myself/change/login_phone'
URL_CHANGE_CONTACT_PHONE = '/m/myself/change/contact_phone'
URL_CHANGE_MAIL = '/m/myself/change/mail'
URL_CHANGE_PASSWORD = '/m/myself/change/password'

API_ORDERS = '/api/orders'
API_PROFILE = '/api/investor_profile'
API_CLIENT_PROFILE = '/api_client/investor_profile'

